import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import Logo from "@/components/ui/logo";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex min-h-full flex-col bg-gray-100 antialiased`}
      >
        <header className="py-6 text-center">
          <Link href="/" className="flex justify-center">
            <Logo />
          </Link>
        </header>
        <main className="grow">{children}</main>
        <footer className="mx-auto flex w-full max-w-7xl justify-between px-4 py-4">
          <p>Powered by Together.ai & Flux</p>

          <div>
            <Link href="#">GitHub</Link>
            <Link href="#">Twitter</Link>
          </div>
        </footer>
      </body>
    </html>
  );
}
